name: mytuning-shop
recipe: lamp
config:
  php: '7.2'
  webroot: source
proxy:
  appserver:
    - mytuning.lndo.site
  phpmyadmin:
    - pma-mytuning.lndo.site
services:
  appserver:
    build_as_root:
    - composer install
    xdebug: true
  npm:
    type: node:8
  phpmyadmin:
    scanner: false
    type: phpmyadmin
    ssl: true
    hosts:
      - database
    database:
      type: mysql
    mailhog:
      type: mailhog:v1.0.0
      portforward: false
      hogfrom:
        - appserver
tooling:
  npm:
    service: npm